name: hafiz_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_offline: ^3.0.1
  flutter_svg: ^2.0.10+1
  intl: any
  onbackground_shared_prefrences: ^0.0.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
    - family: Amiri
      fonts:
        - asset: assets/fonts/AmiriBold.ttf
          weight: 700
        - asset: assets/fonts/AmiriRegular.ttf
          weight: 400
